---
- name: Install required system packages
  package:
    name: "{{ restic_packages }}"

- name: Download restic
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_{{ ansible_system|lower }}_{{ go_arch }}.bz2"
    dest: "/tmp/restic_{{ restic_version }}.bz2"
    checksum: "sha256:https://github.com/restic/restic/releases/download/v{{ restic_version }}/SHA256SUMS"
    # verify GPG as soon as supported, https://github.com/ansible/ansible/issues/69364
    # checksum_sig: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/SHA256SUMS.asc"

# no module to uncompress bz2 available, https://github.com/ansible-collections/community.general/issues/1042
- name: Uncompress restic
  shell:
    cmd: bzcat /tmp/restic_{{ restic_version }}.bz2 > /usr/local/bin/restic_{{ restic_version }}
    creates: /usr/local/bin/restic_{{ restic_version }}

- name: Mark restic executeable
  file:
    path: /usr/local/bin/restic_{{ restic_version }}
    owner: root
    group: root
    mode: 0755

- name: Create symbolic link to current version
  file:
    src: /usr/local/bin/restic_{{ restic_version }}
    path: /usr/local/bin/restic
    state: link
    force: true

- name: Install runrestic
  pip:
    name: runrestic
    version: "{{ runrestic_version }}"
    executable: pip3

- name: Configure runrestic
  template:
    src: runrestic.toml.j2
    dest: /etc/runrestic.toml
    mode: 0600

- name: Add systemd service
  template:
    src: systemd/runrestic.service.j2
    dest: /etc/systemd/system/runrestic.service
    mode: 0644
  notify: reload systemd

- name: Add systemd timer
  template:
    src: systemd/runrestic.timer.j2
    dest: /etc/systemd/system/runrestic.timer
    mode: 0644
  notify: reload systemd

- name: Start and enable systemd timer
  systemd:
    name: runrestic.timer
    state: started
    enabled: true

# TODO: init repo?
